[build-system]
requires = ["setuptools>=61.2", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "demo_henrique"
description = ""
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

requires-python = ">= 3.10"
dynamic = ["version"]
dependencies = ["cst_python[memory_storage]"]

[project.readme]
file = "README.md"
content-type = "text/markdown"


[tool.setuptools]
include-package-data = true
package-dir = { "" = "src" }
license-files = ["LICENSE"]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false
